### ISSUE TITLE
OR and AND diagram labels are reversed

### ISSUE THREAD

**Issue by armatures** [boris-marinov/category-theory-illustrated#11]
This is a fantastic resource for learning category theory. There's one confusing diagram I noticed in the "categories" chapter: ![OR and AND](https://boris-marinov.github.io/category-theory-illustrated/02_category/coproduct_product_duality.svg)

I think these labels are reversed, as earlier in the chapter, this diagram is associated with the product ("and"): ![product](https://boris-marinov.github.io/category-theory-illustrated/02_category/product_external.svg)

Thank you!

**Comment by boris-marinov** [comment]
Indeed, thanks for noticing and taking the time to write. I will have it corrected in the next release

**Comment by boris-marinov** [comment]
Fixed (looks like the change is reflected even in your screenshot, weird)
