### ISSUE TITLE
Monoid associativity doesn't imply that inverses exist

### ISSUE THREAD

**Issue by gunnihinn** [boris-marinov/category-theory-illustrated#2]
In [Monoids etc](https://github.com/boris-marinov/category-theory-illustrated/blob/master/_chapters/03_monoid.md), we have:

> When a rule is associative [...] we can add or remove a term that is present at both sides of an equation and retaining the equality of the existing terms:

An image follows that suggests that for elements `x`, `y`, `z` and `w`, if `x y z = w z` then `x y = w`. This is false; there's nothing that says `w` has a right inverse. As a counterexample, take a commutative ring with a zero divisor, like `k[X] / (X^3)` where `k` is a field, and consider `x = X`, `y = X`, `z = X` and `w = X^2`. Then `x y z = 0` and `w z = 0` but `x y = X^2` and `w = X`.

**Comment by vincentrolfs** [comment]
I was about to post the same thing. I think there are some (to me) simpler counterexamples than the one you posted, for example the natural numbers with the maximum operation. Under this operation (let's denote it with @), we have `2@5=5=3@5`, but certainly `2!=3`. If you want three operands you can add a `1`.

By the way monoids where you can do the claimed manipulation are called cancelable. Every cancelable monoid can be naturally extended to a group, which is really nice. That group is called the Grothendieck group. Noncancellable monoids are important in the study of semifield theory.

**Comment by boris-marinov** [comment]
Thanks, corrected.

**Comment by gunnihinn** [comment]
The new explanation is still not what associativity means. It mentions two equation rewriting conditions (the latter of which is a consequence of the former) that are true by basic logical assumptions.

Associativity means that it doesn't matter in what order we calculate pairwise combinations of terms in an expression. Alternatively, it means we can insert matching parentheses wherever we want and always get the same thing back. By definition, it just means that `x (y z) = (x y) z` for any three elements, and can be extended to `x (y (z w)) = x ((y z) w) = (x y) (z w) = ((x y) z) w) = ...`, and so on for any number of elements by induction.

**Comment by vincentrolfs** [comment]
I disagree, I think the new explanation looks good. The first part says that associativity means that the order in which we apply the operations doesn't matter, which is correct. The second part "when a rule is associative..." explains the consequences of associativity and mentions that we can replace individual elements by products without worry, which is also correct.

**Comment by boris-marinov** [comment]
What @vincentrolfs, plus I wrote a detailed explanation of what associativity is in the previous chapter https://boris-marinov.github.io/category-theory-illustrated/02_category/

**Comment by boris-marinov** [comment]
Feel free to open other issues for either this or something else, I really appreciate your feedback.
