### ISSUE TITLE
What is the software you used for creating the figure?

### ISSUE THREAD

**Issue by ruizewang** [boris-marinov/category-theory-illustrated#6]
Hi, 

Thanks for your great work.

Could you tell me what is the software you used for creating this beautiful figure https://boris-marinov.github.io/category-theory-illustrated/cover.svg ？

Thanks in advance.

**Comment by boris-marinov** [comment]
Sure, it's Inkscape.

You can even open the svg files that are uploaded here directly in it.

**Comment by ruizewang** [comment]
> Sure, it's Inkscape.
> 
> You can even open the svg files that are uploaded here directly in it.

Thanks for your quick and warmly reply :)
