### ISSUE TITLE
Content's license

### ISSUE THREAD

**Issue by gonzalocasas** [boris-marinov/category-theory-illustrated#7]
I find your explanations and graphics excellent and I am wondering if there is an open source or CreativeCommons-type of license attached to it that would allow fair sharing of parts of the content.

**Comment by boris-marinov** [comment]
TL;DR; Just go ahead and use it.

Not sure about which license I will use, as I have to run it through my (potential) publisher, but I am sure that using some of my content would be a non-issue and I wouldn't agree to any deal which would make this problematic.

Let me know if that works for you and also I am very curious to know what would you use it for :)

**Comment by gonzalocasas** [comment]
Thanks! I would like to use some of your explanation of partial order in [this material for a course](https://github.com/compas-teaching/COMPAS-II-FS2021/) on robotic fabrication at ETH Zurich.

**Comment by boris-marinov** [comment]
Wow, sounds interesting. Be sure to send me a link, so I can check it!

**Comment by gonzalocasas** [comment]
I pushed the lecture that includes some of your material in here: https://github.com/compas-teaching/COMPAS-II-FS2021/tree/main/lecture_06  I used some of your excellent graphics in the slides (including a link to this repository) and I implemented the color-mixing lattice as a code example using the graph structures of [compas framework](https://compas.dev/).

Thanks again for publishing this!
